// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} arg
 * @returns {$CancellablePromise<void>}
 */
export function AddShortcut(arg) {
    return $Call.ByID(1551262862, arg);
}

/**
 * @param {string} s
 * @returns {$CancellablePromise<void>}
 */
export function AddShortcutFromBase64(s) {
    return $Call.ByID(1504335541, s);
}

/**
 * CheckForUpdate 检查是否有新版本可用（检测升级）
 * @returns {$CancellablePromise<$models.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2347956003).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearConnectionLogs 清空指定客户端的连接日志（内存缓冲与日志文件）
 * @param {string} clientId
 * @returns {$CancellablePromise<void>}
 */
export function ClearConnectionLogs(clientId) {
    return $Call.ByID(390310005, clientId);
}

/**
 * DownloadAndInstallUpdate 下载最新版本并热替换当前可执行文件
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAndInstallUpdate() {
    return $Call.ByID(2440793480);
}

/**
 * GetAppVersion 返回来自 lib/version 的版本号
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(1780012486);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetClientStates() {
    return $Call.ByID(4274000306).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetConnectionLogs 获取指定客户端的连接日志（直接读内存缓冲，无需解析文件）
 * @param {string} clientId
 * @returns {$CancellablePromise<$models.ConnectionLog[]>}
 */
export function GetConnectionLogs(clientId) {
    return $Call.ByID(1455453564, clientId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetDefaultLogDir 获取默认日志目录路径
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultLogDir() {
    return $Call.ByID(2287653297);
}

/**
 * 以下为对 settings 与 clientStates 的访问方法（供前端调用）
 * @returns {$CancellablePromise<$models.GuiSettings>}
 */
export function GetGuiSettings() {
    return $Call.ByID(3468339871).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ShortClient[]>}
 */
export function GetShortcuts() {
    return $Call.ByID(737927018).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} name
 * @param {string} addr
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function RemoveShortcut(name, addr, key) {
    return $Call.ByID(658180051, name, addr, key);
}

/**
 * RestartApp 重启当前程序（更新完成后调用）
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
    return $Call.ByID(4246341431);
}

/**
 * @param {{ [_ in string]?: string }} m
 * @returns {$CancellablePromise<void>}
 */
export function SaveClientStates(m) {
    return $Call.ByID(2752835897, m);
}

/**
 * @param {$models.GuiSettings} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveGuiSettings(s) {
    return $Call.ByID(979570966, s);
}

/**
 * SelectDirectory 打开目录选择对话框
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1735672136);
}

/**
 * @param {string} name
 * @param {string} addr
 * @param {string} key
 * @param {boolean} tls
 * @param {boolean} runningState
 * @returns {$CancellablePromise<void>}
 */
export function ToggleClient(name, addr, key, tls, runningState) {
    return $Call.ByID(1335627254, name, addr, key, tls, runningState);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.ConnectionLog.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.GuiSettings.createFrom;
const $$createType6 = $models.ShortClient.createFrom;
const $$createType7 = $Create.Array($$createType6);
