// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionLog 连接日志项
 */
export class ConnectionLog {
    /**
     * Creates a new ConnectionLog instance.
     * @param {Partial<ConnectionLog>} [$$source = {}] - The source object to create the ConnectionLog.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "info", "error", "warning", "success"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionLog(/** @type {Partial<ConnectionLog>} */($$parsedSource));
    }
}

/**
 * 持久化文件结构（向后兼容旧的仅数组格式）
 */
export class GuiSettings {
    /**
     * Creates a new GuiSettings instance.
     * @param {Partial<GuiSettings>} [$$source = {}] - The source object to create the GuiSettings.
     */
    constructor($$source = {}) {
        if (!("startupEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startupEnabled"] = false;
        }
        if (!("rememberClientState" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rememberClientState"] = false;
        }
        if (!("logDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logDir"] = "";
        }
        if (!("themeMode" in $$source)) {
            /**
             * "auto", "light", "dark"
             * @member
             * @type {string}
             */
            this["themeMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GuiSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GuiSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GuiSettings(/** @type {Partial<GuiSettings>} */($$parsedSource));
    }
}

/**
 * ShortClient 与前端结构对应
 */
export class ShortClient {
    /**
     * Creates a new ShortClient instance.
     * @param {Partial<ShortClient>} [$$source = {}] - The source object to create the ShortClient.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addr"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("tls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tls"] = false;
        }
        if (!("running" in $$source)) {
            /**
             * 兼容旧版本，实际用Status
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * 连接错误信息
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 连接状态: "stopped", "connecting", "connected"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortClient instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShortClient}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortClient(/** @type {Partial<ShortClient>} */($$parsedSource));
    }
}

/**
 * UpdateInfo 版本检查结果，供前端展示
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }
        if (!("releaseNotes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseNotes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("assetName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}
